#!/bin/bash

# LaTeX 环境安装脚本
# 用于在本地安装 TeX Live 和中文支持

echo "===================================="
echo "LaTeX 环境安装指南"
echo "===================================="
echo ""
echo "本脚本将指导您安装本地 LaTeX 环境，用于编辑和编译论文。"
echo ""
echo "步骤 1: 安装 TeX Live 完整版本"
echo "请在终端中运行以下命令（需要 sudo 权限）:"
echo ""
echo "sudo apt update"
echo "sudo apt install -y texlive-full texlive-lang-chinese latexmk"
echo ""
echo "步骤 2: 验证安装"
echo "安装完成后，运行以下命令验证:"
echo ""
echo "pdflatex --version"
echo "xelatex --version"
echo ""
echo "步骤 3: 编译论文"
echo "在 paper_CSDI_RDE 目录中运行:"
echo ""
echo "# 使用 PDFLaTeX 编译"
echo "pdflatex paper_CSDI_RDE.tex"
echo ""
echo "# 或使用 XeLaTeX 编译（推荐用于中文）"
echo "xelatex paper_CSDI_RDE.tex"
echo ""
echo "步骤 4: 多次编译"
echo "对于包含交叉引用的文档，需要多次编译:"
echo ""
echo "xelatex paper_CSDI_RDE.tex"
echo "xelatex paper_CSDI_RDE.tex"
echo ""
echo "步骤 5: 使用 latexmk 自动编译"
echo "latexmk -xelatex paper_CSDI_RDE.tex"
echo ""
echo "===================================="
echo "常见问题解决"
echo "===================================="
echo "1. 中文显示问题:"
echo "   - 确保使用 xelatex 编译"
echo "   - 确保文档开头包含: \\usepackage[UTF8]{ctex}"
echo ""
echo "2. 编译速度慢:"
echo "   - TeX Live 完整安装较大，首次安装需要时间"
echo "   - 后续编译会使用缓存，速度会加快"
echo ""
echo "3. 缺少包:"
echo "   - texlive-full 包含了大多数常用包"
echo "   - 如果缺少特定包，使用: sudo apt install texlive-science"
echo ""
echo "===================================="
echo "编辑器推荐"
echo "===================================="
echo "1. VS Code + LaTeX Workshop 插件"
echo "2. TeXmaker"
echo "3. TeXstudio"
echo "4. Overleaf (在线)
echo ""
echo "===================================="
echo "安装完成后，您就可以在本地编辑和编译 LaTeX 论文了！"
echo "===================================="
